name: Testing a config change
on:
  push: 
    branches:
      - 'main'
    tags:
      - '**'
permissions:
  contents: write

jobs:
  update_config:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: LS Output
        run: ls
      - name: Check out config
        uses: actions/checkout@v4
        with: 
          repository: AilinLuca/config-test
          token: ${{secrets.GITHUB_TOKEN}}
      - name: LS Output after Checkout
        run: ls
      - name: Update version
        run: |
          sed -i '0,/version:/{s/version:.*/version: 2.0.0/}' ./config.yaml
      - name: Commit change
        run: |
          git config --global user.name "AilinLuca"
          git config --global user.email "33815456+AilinLuca@users.noreply.github.com"
          git add .
          git commit -m "update config for real"
          git push