name: Testing a config change
on:
  push: 
    branches:
      - 'main'
    tags:
      - '**'

jobs:
  update_config:
    if: github.ref_type == 'branch'
    runs-on: self-hosted
    steps:
      - name: LS Output
        run: ls
      - name: Check out config
        uses: actions/checkout@v4
        with: 
          name: AilinLuca/config-test
          ref: main
      - name: Update version
        run: |
          sed -i '0,/version:/{s/version:.*/version: 2.0.0/}' ./config.yaml
      - name: LS Output after Checkout
        run: ls
